### DISCUSSION TITLE
Compose UI

### DISCUSSION THREAD

**Discussion by mairin** [podman-desktop/podman-desktop#2881] [Design Feedback]
# Introduction

Hi everyone 👋🏻 I'm Mo and I am the UX designer working on the Podman Desktop UI. Now that we've hit a solid 1.0 (well actually 1.1 as of this writing :smile:) I wanted to start communicating here about the designs I am working on for Podman Desktop 🦭 . You can consider this category here on the discussion forum as a sneak peak of what *may* show up in the tool a few releases down the road, and we would love your feedback on those designs. Participating here is a good way you can influence the direction of the tool, no patches or coding required :-)

### Penpot
I use an open source, hosted (although you can and [I have run it locally on Podman Desktop](https://blog.linuxgrrl.com/2022/01/19/running-penpot-locally-docker-free-with-podman/) :wink:) design tool called **[Penpot](https://penpot.app)**. Whenever I post a set of designs here, I will post a public access link to the corresponding Penpot file in case you want to take a closer look. It can be a little tricky to navigate these; I might do a separate post about this. The thing to note is that I don't always make the mockups clickable, so you have to click on the little down caret icon shown in the screenshot below to access a design board directory for the file:

![Screenshot from 2023-06-15 12-56-29](https://github.com/containers/podman-desktop/assets/799683/209605a6-7799-475a-909b-72e53dbde6e1)

### Design Specifications
I also try (once a design is a little more solid to share) to post design specifications as GitHub issues ([random example](https://github.com/containers/podman-desktop/issues/1231)). So once a design is at that stage, I will share links to design specifications here too.

# Compose UI

All of that being said:

I am currently working on a design to improve the user experience of our **Compose feature**. Note that as of now, our Compose feature serves primarily as a convenience to install and set up access to compose functionality (for either/or podman or docker) **on the command line**. We don't yet have support for running compose files directly from the UI. (We can, and have for some time now, displayed compose groups of containers in the Containers tab of Podman Desktop for some time now, but that functionality is unrelated to the Compose extension this feature design is focused on.) 

### Penpot file
https://design.penpot.app/#/view/c86728dd-89fd-8169-8002-a2594e3e4ba5?page-id=e28e7abb-3208-808c-8002-aae6038746ab&section=interactions&index=0&share-id=7bde5548-9bcb-8041-8002-ab25006f688d

### WIP Design Specification
![Screenshot from 2023-06-15 12-26-19](https://github.com/containers/podman-desktop/assets/799683/1abfaa0b-619d-4114-811c-ec36f9c9659b)

I won't re-post [the entire design specification](https://github.com/containers/podman-desktop/issues/2811#issuecomment-1593378808) in this discussion post, but I will link you to it with a single mockup above as a teaser. Please do read through [the specification](https://github.com/containers/podman-desktop/issues/2811#issuecomment-1593378808), and feel very welcome to ask questions or leave feedback / comments here in the thread or in our public chat [1].

# [Read the design specification here!](https://github.com/containers/podman-desktop/issues/2811#issuecomment-1593378808)

![SelkieLaunchthanks](https://github.com/containers/podman-desktop/assets/799683/49977999-f0b9-4b39-a5b1-86d41590f6dd)

[1] The Matrix chat room invite is: [https://matrix.to/#/#podman-desktop:fedora.im](https://matrix.to/#/%23podman-desktop:fedora.im) and the Discord invite is: https://discord.gg/tjMd7ANtVg  and the room is #podman-desktop. We're also on #podman-desktop on LiberaChat. These three rooms are all bridged together, so pick whichever you prefer, it's all the same content/people!

**Comment by InfoSec812** [comment]
I know a lot of people use compose, but I would also love to be able to convert to a `Pod` yaml for use with `podman play kube` as this seems to work SO MUCH BETTER in my experience (faster start, more features)

**Reply by mairin** [reply]
Hey @InfoSec812 ! So the intention is that the pod yaml generated for you in the "kube" tab of a pod in Podman Desktop *should* work with `podman play kube`, but bugs are of course possible. Is this what you tried, and it didn't work?

**Reply by InfoSec812** [reply]
Ya know, shame on me because I didn't even look before posting. Sorry Mo! I'll take a look today

**Reply by InfoSec812** [reply]
OK, it seems to work just fine. I started a compose file for a wordpress+mariadb with the `--in-pod wordpress` argument from the CLI. When I open the pod in Desktop it shows the Kube config perfectly!!! Thanks!

![image](https://github.com/containers/podman-desktop/assets/99691/39fbb2ad-c3d8-4752-91a8-57dfdf63145d)

**Reply by mairin** [reply]
@InfoSec812 Ooh great to hear!!! :-)

**Reply by InfoSec812** [reply]
I did have to make one manual change. The hostnames used in compose did not translate to the Pod properly and I had to manually add a `hostAliases` section to the `Pod`  as shown below. 

```
  hostAliases:
  - hostnames:
    - db
    ip: 127.0.0.1
  - hostnames:
    - wordpress
    ip: 127.0.0.1
```

**Reply by slemeur** [reply]
@InfoSec812 Do you mind posting your files and commands you used? Would be interested to go through the use case by myself!

**Reply by InfoSec812** [reply]
Sure, here's the compose file:

```
services:
  db:
    # We use a mariadb image which supports both amd64 & arm64 architecture
    image: mariadb:10.6.4-focal
    # If you really want to use MySQL, uncomment the following line
    #image: mysql:8.0.27
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=somewordpress
      - MYSQL_DATABASE=wordpress
      - MYSQL_USER=wordpress
      - MYSQL_PASSWORD=wordpress
    expose:
      - 3306
      - 33060
  wordpress:
    image: wordpress:latest
    ports:
      - 7080:80
    restart: always
    environment:
      - WORDPRESS_DB_HOST=db
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
volumes:
  db_data:
```

When I run that using `podman-compose --in-pod wordpress up` it starts and works fine. When I then export that running config using `podman kube generate pod_wordpress-compose` the `Pod` YAML it outputs will not start up because the hostnames are different.
