### DISCUSSION TITLE
Why are the pods I created not displayed on the desktop pod page?

### DISCUSSION THREAD

**Discussion by tqq1994516** [podman-desktop/podman-desktop#6163] [Q&A]
I installed kind cluster，Select `pod` `play kubenetes yaml` on the desktop page,Use kubectl to check that the pod is running but the pod page cannot be seen.
```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      name: postgres
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16.2-alpine3.19
          env:
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_DB
              value: test
              ports:
                - containerPort: 5432
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
spec:
  selector:
    app: postgres
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432

```
