### ISSUE TITLE
Kubernetes Cluster Authentication Spam When Using AWS Auth Helper & SSO

### ISSUE THREAD

**Issue by damaestro** [podman-desktop/podman-desktop#10574]
### Bug description

When you have a cluster configured in your local `~/.kube/config` that has the AWS credential helper configured and are using SSO, Podman Desktop causes a flood of authentication requests. This happens when the SSO credentials are expired. This causes hundreds on constantly spawning `aws` commands to be constantly ran.

### Operating system

MacOS 15.2 M3

### Installation Method

Brew (macOS)

### Version

1.15.0

### Steps to reproduce

Example `~/.kube/config` created by `aws eks update-kubeconfig --name eks-cluster` and the "command" fixed due to https://github.com/podman-desktop/podman-desktop/issues/10081:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: XXX
    server: https://XXX.gr7.us-west-2.eks.amazonaws.com:48787
  name: arn:aws:eks:us-west-2:XXX:cluster/eks-cluster
contexts:
- context:
    cluster: arn:aws:eks:us-west-2:XXX:cluster/eks-cluster
    user: arn:aws:eks:us-west-2:XXX:cluster/eks-cluster
  name: arn:aws:eks:us-west-2:XXX:cluster/eks-cluster
current-context: arn:aws:eks:us-west-2:XXX:cluster/eks-cluster
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-west-2:XXX:cluster/eks-cluster
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - "--region"
      - us-west-2
      - eks
      - get-token
      - "--cluster-name"
      - eks-cluster
      - "--output"
      - json
      command: /opt/homebrew/bin/aws
      env:
      - name: AWS_PROFILE
        value: aws-profile-name
```

Resulting process tree when credentials are expired (truncated):

```
 |-+= 01913 localuser /Applications/Podman Desktop.app/Contents/MacOS/Podman Desktop
 | |--- 01917 localuser /Applications/Podman Desktop.app/Contents/Frameworks/Podman Desktop Helper (GPU).app/Contents/MacOS/Podman Desktop Helper (GPU) --type=gpu-process --user-data-dir=/Users/localuser
 | |--- 01918 localuser /Applications/Podman Desktop.app/Contents/Frameworks/Podman Desktop Helper.app/Contents/MacOS/Podman Desktop Helper --type=utility --utility-sub-type=network.mojom.NetworkService --l
 | |--- 01919 localuser /Applications/Podman Desktop.app/Contents/Frameworks/Podman Desktop Helper (Renderer).app/Contents/MacOS/Podman Desktop Helper (Renderer) --type=renderer --user-data-dir=/Users/local
 | |--- 47925 localuser /opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python /opt/homebrew/bin/aws --region us-west-2 eks get-token --
 | |--- 47937 localuser /opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python /opt/homebrew/bin/aws --region us-west-2 eks get-token --
 | |--- 47941 localuser /opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python /opt/homebrew/bin/aws --region us-west-2 eks get-token --
 | |--- 47942 localuser /opt/homebrew/Cellar/python@3.12/3.12.8/Frameworks/Python.framework/Versions/3.12/Resources/Python.app/Contents/MacOS/Python /opt/homebrew/bin/aws --region us-west-2 eks get-token --
 [...]
```

### Relevant log output

```shell

```

### Additional context

The issue goes away once you refresh your SSO session with a successful `aws sso login`.

The return code of the credential helper likely needs to be inspected, or `aws` commands need to be handled with special care because they are not sending good return codes. 

[podman-desktop-pstree.txt](https://github.com/user-attachments/files/18352240/podman-desktop-pstree.txt)
