### ISSUE TITLE
creating kompose extension

### ISSUE THREAD

**Issue by axel7083** [podman-desktop/podman-desktop#3961]
### Is your feature request related to a problem? Please describe

The `Generate kube` action on a `COMPOSE` containerGroup creates a pod with many containers. Which is working but not really common behaviour when porting compose file to Kubernetes.

### Example

![image](https://github.com/containers/podman-desktop/assets/42176370/6156a1fa-20c9-43fa-a4ef-8ea74ff04dbd)

Will generate 

```yaml
apiVersion: v1
kind: Pod
metadata:
...
spec:
  containers:
  - image: registry.k8s.io/redis:e2e
    ...
  - image: registry.k8s.io/redis-slave:v2
    ...
  - image: registry.k8s.io/guestbook:v3
    ...
```

### Describe the solution you'd like

The [Kompose](https://github.com/kubernetes/kompose) project could be used in an extension to enhance the files generated. If https://github.com/containers/podman-desktop/pull/3959 is merged, an extension could add a menu actions to generate a more details output.
