### ISSUE TITLE
Cluster not Reachable when exec Authentication is used

### ISSUE THREAD

**Issue by hofq** [podman-desktop/podman-desktop#6517]
### Bug description

For Authentication on Prod we use azure/kubelogin. It seems like it is not compatible to Podman Desktop

### Operating system

macos sonoma 14

### Installation Method

Brew (macOS)

### Version

1.8.0

### Steps to reproduce

- Open Podman Desktop
- Select AWS Cluster, authenticated with kubelogin from azure or with aws-iam-authenticator
- Receive Error below

### Additional context

<img width="584" alt="grafik" src="https://github.com/containers/podman-desktop/assets/54744977/d4c01b60-7880-4107-b91e-9695245fc69e">

User Authentication snippet Kubelogin:
```yaml
user:
- name: azure-user-roc-kubelogin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--environment"
      - AzurePublicCloud
      - "--server-id"
      - <client id>
      - "--client-id"
      - <client id>
      - "--tenant-id"
      - <tenant id>
      command: kubelogin
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
Used Package for auth:
https://github.com/Azure/kubelogin
<br />

User Authentication snippet Kubelogin:
```yaml
- name: user-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - "-i"
      - roc-prod
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: eu-central-1
      interactiveMode: IfAvailable
      provideClusterInfo: false
```

**Comment by kwkelly** [comment]
I get the same error using exec authentication with `aws`.

I suspect this has to do with the availability (or lack thereof) of the comman` for the exec in the path. 

I have the `aws` command installed at `/usr/local/bin/aws`, and if I start podman desktop and omit `/usr/local/bin` from the PATH (e.g. `PATH=/usr/bin open /Applications/Podman\ Desktop.app/`), I get the `TypeError: Cannot read properties of null (reading 'toString'))` error.

On the other hand, if I make sure that authentication command is available in my path (e.g. `PATH=/usr/local/bin:/usr/bin open /Applications/Podman\ Desktop.app/`), it works just fine.

So in your kube config file, you can add to the env for exec the path to where the binary is installed.

```
env:
      - name: PATH
         value: $PATH:/usr/local/bin
```

**Comment by hofq** [comment]
Still an issue.

**Comment by damaestro** [comment]
For MacOS, it might make sense to include `/opt/homebrew/bin` by default.

**Comment by rujutashinde** [comment]
This seems to be fixed with 1.18.0. Could you please retry with this version and reopen is the issue still exists

**Comment by hofq** [comment]
<img width="217" alt="Image" src="https://github.com/user-attachments/assets/fe8ff15f-18fa-4d46-ac3d-acbaddc7b635" />

<img width="212" alt="Image" src="https://github.com/user-attachments/assets/b63503bd-b901-43f0-b4dc-304403a673f3" />

Using 1.18.0 on MacOS @rujutashinde. I am not allowed to reopen.

**Comment by rujutashinde** [comment]
@hofq reopening on your behalf, please include if there are any new steps/log/additional info that you can provide for this issue

**Comment by hofq** [comment]
<img width="523" alt="Image" src="https://github.com/user-attachments/assets/356f16a1-9887-424c-b248-d066c1923eb8" />
Logs when switching context

**Comment by feloy** [comment]
@hofq I suppose that you are adding the directory where is kubelogin to the PATH variable in some config file for your shell (so it is found for commands executed from your terminal), but this change is not affecting the environment for Podman Desktop.

To be sure that `kubelogin` is found by Podman Desktop, please try to specify the complete path in the `config` file:

```
user:
- name: azure-user-roc-kubelogin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - get-token
      - "--environment"
      - AzurePublicCloud
      - "--server-id"
      - <client id>
      - "--client-id"
      - <client id>
      - "--tenant-id"
      - <tenant id>
      command: /usr/local/bin/kubelogin     <--- change here with the correct path
      env: null
      interactiveMode: IfAvailable
      provideClusterInfo: false
```
